import sys
import re

with open("MainWindow_recovered_utf8.cs", "r", encoding="utf-8") as f:
    content = f.read()

# Make the class partial
content = content.replace("public class MainWindow : Window, IComponentConnector", "public partial class MainWindow : Window")

# Remove internal fields generated by ILSpy
content = re.sub(r'^\s*internal\s+[a-zA-Z0-9_]+\s+[a-zA-Z0-9_]+;\s*$', '', content, flags=re.MULTILINE)
content = re.sub(r'^\s*private bool _contentLoaded;\s*$', '', content, flags=re.MULTILINE)

# We need to remove the IComponentConnector.Connect method and its body.
# It starts with "void IComponentConnector.Connect"
# We can find it and delete everything from it to the end, since it's the last method usually.
# Let's just find "void IComponentConnector.Connect"
connect_idx = content.find("void IComponentConnector.Connect")
if connect_idx != -1:
    # Find the preceding attributes like [DebuggerNonUserCode]
    attr_idx = content.rfind("[DebuggerNonUserCode]", 0, connect_idx)
    if attr_idx != -1:
        # Delete from attr_idx to the end of the file except the very last brace
        content = content[:attr_idx] + "}\n"

# Remove InitializeComponent method
init_idx = content.find("public void InitializeComponent()")
if init_idx != -1:
    attr_idx = content.rfind("[DebuggerNonUserCode]", 0, init_idx)
    if attr_idx != -1:
        # We need to delete just this method.
        # Find the end of the method body.
        start_brace = content.find("{", init_idx)
        brace_count = 1
        end_brace = start_brace + 1
        while brace_count > 0 and end_brace < len(content):
            if content[end_brace] == "{":
                brace_count += 1
            elif content[end_brace] == "}":
                brace_count -= 1
            end_brace += 1
        
        content = content[:attr_idx] + content[end_brace:]

with open("MainWindow.xaml.cs", "w", encoding="utf-8") as f:
    f.write(content)

print("Recovered MainWindow.xaml.cs successfully!")
