<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>SS14_MIDI_IDE</RootNamespace>
    <AssemblyName>MidiMaster</AssemblyName>
    <Product>MidiMaster</Product>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    <ApplicationIcon>mothroach.ico</ApplicationIcon>
    <Version>0.113.0.0</Version>
    <FileVersion>0.113.0.0</FileVersion>
    <PublishSingleFile>true</PublishSingleFile>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="mothroach.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Melanchall.DryWetMidi" Version="8.0.3" />
    <PackageReference Include="MeltySynth" Version="2.4.1" />
    <PackageReference Include="NAudio" Version="3.0.1" />
    <PackageReference Include="NVorbis" Version="0.10.5" />
    <PackageReference Include="WpfAnimatedGif" Version="2.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Remove="System.Windows.Forms" />
    <Using Remove="System.Drawing" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="mothroach.png" />
    <EmbeddedResource Include="moth_squeak.ogg" />
    <EmbeddedResource Include="GeneralUser-GS.sf2" />
  </ItemGroup>

</Project>
